import {Types,ClientSession} from 'mongoose';import {connectDB} from '@/lib/db';import Party from '@/models/Party';import Product from '@/models/Product';import Transaction from '@/models/Transaction';import {TransactionInput,SaleInput,PurchaseInput,PaymentInput} from '@/lib/validations/domain';
export class TransactionServiceError extends Error{code:string;details?:unknown;constructor(code:string,message:string,details?:unknown){super(message);this.code=code;this.details=details;}}
const oid=(id:string)=>{if(!Types.ObjectId.isValid(id))throw new TransactionServiceError('INVALID_ID','Invalid id');return new Types.ObjectId(id)};
async function runAtomic<T>(userId:string,fn:(s:ClientSession,uid:Types.ObjectId)=>Promise<T>,session?:ClientSession){const uid=oid(userId);if(session)return fn(session,uid);await connectDB();const s=await Transaction.startSession();try{let out!:T;await s.withTransaction(async()=>{out=await fn(s,uid)});return out}finally{await s.endSession()}}
async function assertParty(id:string,uid:Types.ObjectId,s:ClientSession,type?:'CUSTOMER'|'SUPPLIER'){const p=await Party.findOne({_id:oid(id),userId:uid,...(type?{partyType:type}:{})}).session(s);if(!p)throw new TransactionServiceError('NOT_FOUND','Party not found');return p}
async function assertProduct(id:string,uid:Types.ObjectId,s:ClientSession){const p=await Product.findOne({_id:oid(id),userId:uid}).session(s);if(!p)throw new TransactionServiceError('NOT_FOUND','Product not found');return p}
export async function createTransaction(input:TransactionInput,userId:string,session?:ClientSession){return runAtomic(userId,async(s,uid)=>{let party,product;if(input.partyId)party=await assertParty(input.partyId,uid,s);if(input.productId)product=await assertProduct(input.productId,uid,s);
if(['DUE_GIVEN','DUE_RECEIVED','PAYMENT_TO_SUPPLIER'].includes(input.type)&&!party)throw new TransactionServiceError('INVALID_PARTY','Party required');
if(input.type==='DUE_GIVEN')await Party.updateOne({_id:party!._id,userId:uid},{$inc:{currentBalance:input.amount}},{session:s});
if(input.type==='DUE_RECEIVED')await Party.updateOne({_id:party!._id,userId:uid},{$inc:{currentBalance:-input.amount}},{session:s});
if(input.type==='PAYMENT_TO_SUPPLIER')await Party.updateOne({_id:party!._id,userId:uid},{$inc:{currentBalance:input.amount}},{session:s});
if(['STOCK_IN','STOCK_OUT'].includes(input.type)){if(!product)throw new TransactionServiceError('INVALID_PRODUCT','Product required');const delta=input.type==='STOCK_IN'?input.quantity:-input.quantity;const next=product.stockQuantity+delta;if(next<0)throw new TransactionServiceError('INSUFFICIENT_STOCK',`Not enough stock. Available: ${product.stockQuantity}`);await Product.updateOne({_id:product._id,userId:uid},{$set:{stockQuantity:next,...(input.unitPrice!==undefined?(input.type==='STOCK_IN'?{buyPrice:input.unitPrice}:{sellPrice:input.unitPrice}):{})}},{session:s})}
const [tx]=await Transaction.create([{userId:uid,partyId:party?._id,productId:product?._id,type:input.type,amount:input.amount,quantity:input.quantity,unitPrice:input.unitPrice,paidAmount:input.paidAmount,paymentMethod:input.paymentMethod,notes:input.notes,timestamp:input.timestamp||new Date()}],{session:s});return{id:String(tx._id),type:tx.type,amount:tx.amount,quantity:tx.quantity}} ,session)}
export async function createSale(input:SaleInput,userId:string,session?:ClientSession){return runAtomic(userId,async(s,uid)=>{const groupId=new Types.ObjectId().toHexString();let total=0,cost=0;const products=[] as any[];for(const line of input.lines){const p=await assertProduct(line.productId,uid,s);if(p.stockQuantity<line.quantity)throw new TransactionServiceError('INSUFFICIENT_STOCK',`${p.name}: only ${p.stockQuantity} ${p.unit} available`);const price=line.unitPrice??p.sellPrice;const lineTotal=price*line.quantity;const lineCost=p.buyPrice*line.quantity;total+=lineTotal;cost+=lineCost;products.push({p,line,price,lineTotal,lineCost});}if(input.paidAmount>total)throw new TransactionServiceError('INVALID_PAYMENT','Paid amount cannot exceed total');let party;if(input.partyId)party=await assertParty(input.partyId,uid,s,'CUSTOMER');const due=total-input.paidAmount;for(const x of products){await Product.updateOne({_id:x.p._id,userId:uid},{$inc:{stockQuantity:-x.line.quantity}},{session:s});await Transaction.create([{userId:uid,groupId,partyId:party?._id,productId:x.p._id,type:'SALE',amount:x.lineTotal,quantity:x.line.quantity,unitPrice:x.price,paidAmount:products.indexOf(x)===0?input.paidAmount:0,costAmount:x.lineCost,paymentMethod:input.paymentMethod,notes:input.notes,timestamp:input.timestamp||new Date()}],{session:s})}if(due>0&&party)await Party.updateOne({_id:party._id,userId:uid},{$inc:{currentBalance:due}},{session:s});return{groupId,total,paidAmount:input.paidAmount,due,cost,profit:total-cost,items:products.map(x=>({name:x.p.name,quantity:x.line.quantity,unitPrice:x.price}))}},session)}
export async function createPurchase(input:PurchaseInput,userId:string,session?:ClientSession){return runAtomic(userId,async(s,uid)=>{const groupId=new Types.ObjectId().toHexString();let total=0;const products=[] as any[];for(const line of input.lines){const p=await assertProduct(line.productId,uid,s);const price=line.unitPrice??p.buyPrice;const lineTotal=price*line.quantity;total+=lineTotal;products.push({p,line,price,lineTotal});}if(input.paidAmount>total)throw new TransactionServiceError('INVALID_PAYMENT','Paid amount cannot exceed total');let party;if(input.partyId)party=await assertParty(input.partyId,uid,s,'SUPPLIER');const due=total-input.paidAmount;for(let i=0;i<products.length;i++){const x=products[i];await Product.updateOne({_id:x.p._id,userId:uid},{$inc:{stockQuantity:x.line.quantity},$set:{buyPrice:x.price}},{session:s});const paidForLine=i===0?input.paidAmount:0;await Transaction.create([{userId:uid,groupId,partyId:party?._id,productId:x.p._id,type:'PURCHASE',amount:x.lineTotal,quantity:x.line.quantity,unitPrice:x.price,paidAmount:paidForLine,paymentMethod:input.paymentMethod,notes:input.notes,timestamp:input.timestamp||new Date()}],{session:s})}if(due>0&&party)await Party.updateOne({_id:party._id,userId:uid},{$inc:{currentBalance:-due}},{session:s});return{groupId,total,paidAmount:input.paidAmount,due,items:products.map(x=>({name:x.p.name,quantity:x.line.quantity,unitPrice:x.price}))}},session)}
export async function recordCustomerPayment(input:PaymentInput,userId:string){return runAtomic(userId,async(s,uid)=>{const p=await assertParty(input.partyId,uid,s,'CUSTOMER');await Party.updateOne({_id:p._id,userId:uid},{$inc:{currentBalance:-input.amount}},{session:s});const [tx]=await Transaction.create([{userId:uid,partyId:p._id,type:'DUE_RECEIVED',amount:input.amount,quantity:0,paymentMethod:input.paymentMethod,notes:input.notes,timestamp:input.timestamp||new Date()}],{session:s});return{id:String(tx._id),party:p.name,amount:input.amount}},undefined)}
export async function recordSupplierPayment(input:PaymentInput,userId:string){return runAtomic(userId,async(s,uid)=>{const p=await assertParty(input.partyId,uid,s,'SUPPLIER');await Party.updateOne({_id:p._id,userId:uid},{$inc:{currentBalance:input.amount}},{session:s});const [tx]=await Transaction.create([{userId:uid,partyId:p._id,type:'PAYMENT_TO_SUPPLIER',amount:input.amount,quantity:0,paymentMethod:input.paymentMethod,notes:input.notes,timestamp:input.timestamp||new Date()}],{session:s});return{id:String(tx._id),party:p.name,amount:input.amount}},undefined)}
export async function reverseTransaction(id:string,userId:string,session?:ClientSession){return runAtomic(userId,async(s,uid)=>{const tx=await Transaction.findOne({_id:oid(id),userId:uid}).session(s);if(!tx)throw new TransactionServiceError('NOT_FOUND','Transaction not found');if(tx.groupId){const all=await Transaction.find({userId:uid,groupId:tx.groupId}).session(s);for(const row of all){if(row.type==='SALE'&&row.productId)await Product.updateOne({_id:row.productId,userId:uid},{$inc:{stockQuantity:row.quantity}},{session:s});if(row.type==='PURCHASE'&&row.productId){const p=await Product.findOne({_id:row.productId,userId:uid}).session(s);if(!p||p.stockQuantity<row.quantity)throw new TransactionServiceError('REVERSAL_BLOCKED','Cannot reverse purchase because stock has already been consumed.');await Product.updateOne({_id:row.productId,userId:uid},{$inc:{stockQuantity:-row.quantity}},{session:s});}if(row.partyId&&row.type==='SALE'&&row.amount>0){const dueForLine=0;void dueForLine;} }const first=all[0];const total=all.reduce((n,r)=>n+r.amount,0);const paid=all.reduce((n,r)=>n+(r.paidAmount||0),0);if(first?.partyId&&first.type==='SALE'&&paid<total)await Party.updateOne({_id:first.partyId,userId:uid},{$inc:{currentBalance:-(total-paid)}},{session:s});if(first?.partyId&&first.type==='PURCHASE'&&paid<total)await Party.updateOne({_id:first.partyId,userId:uid},{$inc:{currentBalance:(total-paid)}},{session:s});await Transaction.deleteMany({userId:uid,groupId:tx.groupId},{session:s});return{deletedId:String(tx._id),groupId:tx.groupId};}
if(tx.type==='DUE_GIVEN'&&tx.partyId)await Party.updateOne({_id:tx.partyId,userId:uid},{$inc:{currentBalance:-tx.amount}},{session:s});if(tx.type==='DUE_RECEIVED'&&tx.partyId)await Party.updateOne({_id:tx.partyId,userId:uid},{$inc:{currentBalance:tx.amount}},{session:s});if(tx.type==='PAYMENT_TO_SUPPLIER'&&tx.partyId)await Party.updateOne({_id:tx.partyId,userId:uid},{$inc:{currentBalance:-tx.amount}},{session:s});if(tx.type==='STOCK_IN'&&tx.productId){await Product.updateOne({_id:tx.productId,userId:uid},{$inc:{stockQuantity:-tx.quantity}},{session:s})}if(tx.type==='STOCK_OUT'&&tx.productId){await Product.updateOne({_id:tx.productId,userId:uid},{$inc:{stockQuantity:tx.quantity}},{session:s})}await Transaction.deleteOne({_id:tx._id,userId:uid},{session:s});return{deletedId:String(tx._id)}},session)}
