import {NextResponse} from 'next/server';
import {auth} from '@/auth';
import {connectDB} from '@/lib/db';
import Transaction from '@/models/Transaction';
import Party from '@/models/Party';
import Product from '@/models/Product';
import {Types} from 'mongoose';
import {z} from 'zod';
const Q=z.object({question:z.string().trim().min(2).max(500)});
export async function POST(req:Request){const s=await auth();if(!s?.user?.id)return NextResponse.json({error:'Unauthorized'},{status:401});const b=Q.safeParse(await req.json());if(!b.success)return NextResponse.json({error:'Invalid question'},{status:400});await connectDB();const uid=new Types.ObjectId(s.user.id);const q=b.data.question.toLowerCase();const today=new Date();today.setHours(0,0,0,0);const tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1);const [sales,expenses,receivable,payable,low]=await Promise.all([Transaction.aggregate([{$match:{userId:uid,type:'SALE',timestamp:{$gte:today,$lt:tomorrow}}},{$group:{_id:null,total:{$sum:'$amount'},cost:{$sum:{$ifNull:['$costAmount',0]}}}}]),Transaction.aggregate([{$match:{userId:uid,type:'EXPENSE',timestamp:{$gte:today,$lt:tomorrow}}},{$group:{_id:null,total:{$sum:'$amount'}}}]),Party.aggregate([{$match:{userId:uid,currentBalance:{$gt:0}}},{$group:{_id:null,total:{$sum:'$currentBalance'}}}]),Party.aggregate([{$match:{userId:uid,currentBalance:{$lt:0}}},{$group:{_id:null,total:{$sum:{$abs:'$currentBalance'}}}}]),Product.countDocuments({userId:uid,$expr:{$lte:['$stockQuantity','$lowStockThreshold']}})]);const sv=sales[0]||{total:0,cost:0},ev=expenses[0]?.total||0;let answer=`আজকের বিক্রি ৳${Number(sv.total).toLocaleString('en-BD')}, খরচ ৳${Number(ev).toLocaleString('en-BD')}, আনুমানিক মোট লাভ ৳${Number(sv.total-sv.cost).toLocaleString('en-BD')}।`;if(q.includes('পাব')||q.includes('পাওনা')||q.includes('receivable'))answer=`আপনার মোট পাওনা প্রায় ৳${Number(receivable[0]?.total||0).toLocaleString('en-BD')}।`;else if(q.includes('দেব')||q.includes('পরিশোধ')||q.includes('payable'))answer=`আপনার মোট দেনা প্রায় ৳${Number(payable[0]?.total||0).toLocaleString('en-BD')}।`;else if(q.includes('স্টক')||q.includes('stock'))answer=`বর্তমানে ${low}টি পণ্য low stock অবস্থায় আছে।`;return NextResponse.json({answer,metrics:{todaySales:sv.total,todayCost:sv.cost,todayExpenses:ev,grossProfit:sv.total-sv.cost,receivable:receivable[0]?.total||0,payable:payable[0]?.total||0,lowStock:low}})}
